STORE_GEOLOCATION = "store-geolocation"
INPUT_LOCATION = "input-location"
INPUT_DATE = "input-date"
TEXT_GEOLOC = "txt-geolocation"
TABS_PLOT = "tabs-plot"
TAB_PLOT_DAY = "tab-plot-day"
TAB_PLOT_YEAR = "tab-plot-year"
TAB_PLOT_OPTI = "tab-plot-opti"

COLLAPSE_MAIN_APP = "collapse-main"
STORE_WEATHER = "store-weather"
SWITCH_WEATHER = "switch-weather"
COLLAPSE_WEATHER = "collapse-weather"
DATEPICKER = "datepicker"
DIV_DATEPICKER = "div-datepicker"
INPUT_WEATHER_OVEREALL = "input-weather-overall"
INPUT_WEATHER_MONTH = "input-weather-month"

BTN_DATE_TODAY = "btn-date-today"
BTN_DATE_PMIN = "btn-date-pmin"
BTN_DATE_PMAX = "btn-date-pmax"
BTN_DATE_EMIN = "btn-date-emin"
BTN_DATE_EMAX = "btn-date-emax"

STORE_PANELS = "store-panels"
DIV_PANEL_LIST = "div-panel_list"
BTN_ADD_PANEL = "btn-add_panel"
BTN_CLEAR_PANELS = "btn-clear_panels"

CHECKBOX_PANEL_ACTIVE = "check-panel_active"
BTN_DELETE_PANEL = "btn-panel_delete"
INPUT_PANEL_LABEL = "input-panel_label"
INPUT_PANEL_AZI = "input-panel_azi"
INPUT_PANEL_ALT = "input-panel_alt"
INPUT_PANEL_SIZE = "input-panel_size"
INPUT_PANEL_COLOR = "input-panel_color"
INPUT_PANEL_SPECPWR = "input-panel_specific_power"
BTN_OPTIMIZE_ANGLES = "btn-optimize-azi"
BTN_OPTIMIZE_AZI = "btn-optimize-azi"
BTN_OPTIMIZE_TILT = "btn-optimize-tilt"

DIV_GRAPH = "div-graph"

MODAL_OPTI = "modal-opti"
DIV_OPTI_GRAPH = "div-opti-graph"
